version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: 'postgres:16.6'
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

  redis:
    image: 'redis:8.0.2-alpine'
    ports:
      - "${REDIS_EXPOSED_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  user-service-db-data:
  redis-data: