version: '3.8'

services:
  postgres:
    image: 'postgres:16.6'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

volumes:
  user-service-db-data: